import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "es" | "en" | "pt" | "fr" | "it";

const LANG_KEY = "lettora_language";

const languageNames: Record<Language, string> = {
  es: "Español",
  en: "English",
  pt: "Português",
  fr: "Français",
  it: "Italiano",
};

// Translation keys - keeping it focused on UI strings used across the app
const translations: Record<Language, Record<string, string>> = {
  es: {
    home: "Inicio",
    explore: "Explorar",
    library: "Biblioteca",
    messages: "Mensajes",
    profile: "Perfil",
    settings: "Configuración",
    darkMode: "Modo oscuro",
    language: "Idioma",
    notifications: "Notificaciones",
    pushNotifications: "Notificaciones push",
    emailNotifications: "Notificaciones por email",
    privacy: "Privacidad",
    privateProfile: "Perfil privado",
    showReadingActivity: "Mostrar actividad de lectura",
    changePassword: "Cambiar contraseña",
    content: "Contenido",
    favoriteGenres: "Géneros favoritos",
    favoriteAuthors: "Autores favoritos",
    storage: "Almacenamiento",
    spaceUsed: "Espacio usado",
    downloadedBooks: "Libros descargados",
    wifiOnly: "Solo Wi-Fi para descargas",
    clearCache: "Limpiar caché",
    logout: "Cerrar sesión",
    logoutConfirm: "¿Cerrar sesión?",
    logoutDescription: "Tendrás que volver a iniciar sesión para acceder a tu cuenta.",
    cancel: "Cancelar",
    deleteDownloaded: "¿Eliminar libros descargados?",
    deleteDownloadedDesc: "Se eliminarán los libros de tu dispositivo.",
    delete: "Eliminar",
    appearance: "Apariencia",
    readingTheme: "Tema de lectura",
    customizeExperience: "Personaliza tu experiencia",
    version: "Versión",
    myAccount: "Mi cuenta",
    comingSoon: "Próximamente",
    search: "Buscar",
    searchConversations: "Buscar conversaciones...",
    noConversations: "No hay conversaciones",
    startConversation: "Inicia una conversación con otro usuario",
    newConversation: "Nueva conversación",
    now: "Ahora",
    yesterday: "Ayer",
    noMessages: "Sin mensajes",
    publications: "Publicaciones",
    create: "Crear",
    newPost: "Nueva publicación",
    publish: "Publicar",
    whatToShare: "¿Qué quieres compartir?",
    photo: "Foto",
    video: "Video",
    noPostsYet: "Sin publicaciones aún",
    beFirst: "¡Sé el primero en compartir!",
    createPost: "Crear publicación",
    publishError: "Error al publicar",
    published: "¡Publicado!",
    trending: "Tendencias",
    seeMore: "Ver más",
    recentlyPublished: "Recién publicados",
    noBooksYet: "Sin libros aún",
    categories: "Categorías",
    writeStory: "Escribir historia",
    microstories: "Microrrelatos",
    feedStories: "Feed & Stories",
    publishAndShare: "Publica y comparte",
    createPromotion: "Crear Promoción",
    highlightBook: "Destaca tu libro y llega a más lectores",
    personalizeRecs: "Personaliza tus recomendaciones",
    loadError: "Error al cargar conversaciones",
    privateProfileDesc: "Solo tus seguidores pueden ver tu contenido",
    profileStore: "Tienda de perfil",
    coins: "monedas",
    totalEarned: "Total ganado",
    earnByEngaging: "Gana interactuando",
    comment: "Comentario",
    frames: "Marcos",
    backgrounds: "Fondos",
    notEnoughCoins: "No tienes suficientes monedas",
    noItemsAvailable: "No hay items disponibles",
    close: "Cerrar",
    store: "Tienda",
    back: "Atrás",
    editProfile: "Editar perfil",
    newBook: "Nuevo libro",
    books: "Libros",
    followers: "Seguidores",
    following: "Siguiendo",
    reads: "Lecturas",
    inventory: "Inventario",
    profileThemes: "Temas de perfil",
    noBooksYetProfile: "No tienes libros aún",
    startWriting: "¡Empieza a escribir tu primera historia!",
    createBook: "Crear libro",
    deleteBook: "¿Eliminar libro?",
    deleteBookDesc: "Se eliminará permanentemente. Esta acción no se puede deshacer.",
    deleted: "Eliminado",
    deleteError: "Error al eliminar",
    team: "Equipo / Admins",
    teamDesc: "Conoce al equipo detrás de la app",
    staffBday: "Staff Bday",
    staffBdayTitle: "Staff Bday",
    staffBdayClosed: "Esta sección está cerrada actualmente",
    staffContract: "Staff Contract",
    staffContractDesc: "Contratos y formularios del equipo",
    noContracts: "Sin contratos",
    noContractsDesc: "No hay contratos disponibles por el momento.",
    endsAt: "Finaliza",
    openForm: "Abrir formulario",
    expired: "Expirado",
    active: "Activo",
    news: "Noticias",
    newsDesc: "Actualizaciones, parches y novedades",
    noNews: "Sin noticias",
    noNewsDesc: "No hay noticias disponibles por el momento.",
    proposals: "Propuestas",
    proposalsDesc: "Envía ideas y sugerencias",
    sendProposal: "Enviar propuesta",
    socialLinks: "Redes Sociales",
    paragraphComments: "Comentarios por párrafo",
    createSaga: "Crear Saga",
    sagaBooks: "libros en la saga",
    writeNovel: "Escribir Novela",
    writeBook: "Escribir Libro",
    whatToCreate: "¿Qué quieres crear?",
    community: "Comunidad",
    pending: "Pendiente",
    reviewed: "Revisada",
    implemented: "Implementada",
    textMode: "Modo texto",
    imageMode: "Modo imagen",
  },
  en: {
    home: "Home",
    explore: "Explore",
    library: "Library",
    messages: "Messages",
    profile: "Profile",
    settings: "Settings",
    darkMode: "Dark Mode",
    language: "Language",
    notifications: "Notifications",
    pushNotifications: "Push Notifications",
    emailNotifications: "Email Notifications",
    privacy: "Privacy",
    privateProfile: "Private Profile",
    showReadingActivity: "Show Reading Activity",
    changePassword: "Change Password",
    content: "Content",
    favoriteGenres: "Favorite Genres",
    favoriteAuthors: "Favorite Authors",
    storage: "Storage",
    spaceUsed: "Space Used",
    downloadedBooks: "Downloaded Books",
    wifiOnly: "Wi-Fi Only Downloads",
    clearCache: "Clear Cache",
    logout: "Log Out",
    logoutConfirm: "Log Out?",
    logoutDescription: "You'll need to sign in again to access your account.",
    cancel: "Cancel",
    deleteDownloaded: "Delete Downloaded Books?",
    deleteDownloadedDesc: "Books will be removed from your device.",
    delete: "Delete",
    appearance: "Appearance",
    readingTheme: "Reading Theme",
    customizeExperience: "Customize your experience",
    version: "Version",
    myAccount: "My Account",
    comingSoon: "Coming Soon",
    search: "Search",
    searchConversations: "Search conversations...",
    noConversations: "No conversations",
    startConversation: "Start a conversation with another user",
    newConversation: "New conversation",
    now: "Now",
    yesterday: "Yesterday",
    noMessages: "No messages",
    publications: "Posts",
    create: "Create",
    newPost: "New Post",
    publish: "Publish",
    whatToShare: "What do you want to share?",
    photo: "Photo",
    video: "Video",
    noPostsYet: "No posts yet",
    beFirst: "Be the first to share!",
    createPost: "Create Post",
    publishError: "Error publishing",
    published: "Published!",
    trending: "Trending",
    seeMore: "See More",
    recentlyPublished: "Recently Published",
    noBooksYet: "No books yet",
    categories: "Categories",
    writeStory: "Write Story",
    microstories: "Microstories",
    feedStories: "Feed & Stories",
    publishAndShare: "Publish and share",
    createPromotion: "Create Promotion",
    highlightBook: "Highlight your book and reach more readers",
    personalizeRecs: "Personalize your recommendations",
    loadError: "Error loading conversations",
    privateProfileDesc: "Only your followers can see your content",
    profileStore: "Profile Store",
    coins: "coins",
    totalEarned: "Total earned",
    earnByEngaging: "Earn by engaging",
    comment: "Comment",
    frames: "Frames",
    backgrounds: "Backgrounds",
    notEnoughCoins: "Not enough coins",
    noItemsAvailable: "No items available",
    close: "Close",
    store: "Store",
    back: "Back",
    editProfile: "Edit profile",
    newBook: "New book",
    books: "Books",
    followers: "Followers",
    following: "Following",
    reads: "Reads",
    inventory: "Inventory",
    profileThemes: "Profile themes",
    noBooksYetProfile: "No books yet",
    startWriting: "Start writing your first story!",
    createBook: "Create book",
    deleteBook: "Delete book?",
    deleteBookDesc: "It will be permanently deleted. This action cannot be undone.",
    deleted: "Deleted",
    deleteError: "Error deleting",
    team: "Team / Admins",
    teamDesc: "Meet the team behind the app",
    staffBday: "Staff Bday",
    staffBdayTitle: "Staff Bday",
    staffBdayClosed: "This section is currently closed",
    staffContract: "Staff Contract",
    staffContractDesc: "Team contracts and forms",
    noContracts: "No contracts",
    noContractsDesc: "No contracts available at this time.",
    endsAt: "Ends",
    openForm: "Open form",
    expired: "Expired",
    active: "Active",
    news: "News",
    newsDesc: "Updates, patches and announcements",
    noNews: "No news",
    noNewsDesc: "No news available at this time.",
  },
  pt: {
    home: "Início",
    explore: "Explorar",
    library: "Biblioteca",
    messages: "Mensagens",
    profile: "Perfil",
    settings: "Configurações",
    darkMode: "Modo escuro",
    language: "Idioma",
    notifications: "Notificações",
    pushNotifications: "Notificações push",
    emailNotifications: "Notificações por email",
    privacy: "Privacidade",
    privateProfile: "Perfil privado",
    showReadingActivity: "Mostrar atividade de leitura",
    changePassword: "Alterar senha",
    content: "Conteúdo",
    favoriteGenres: "Gêneros favoritos",
    favoriteAuthors: "Autores favoritos",
    storage: "Armazenamento",
    spaceUsed: "Espaço usado",
    downloadedBooks: "Livros baixados",
    wifiOnly: "Apenas Wi-Fi para downloads",
    clearCache: "Limpar cache",
    logout: "Sair",
    logoutConfirm: "Sair?",
    logoutDescription: "Você precisará fazer login novamente para acessar sua conta.",
    cancel: "Cancelar",
    deleteDownloaded: "Excluir livros baixados?",
    deleteDownloadedDesc: "Os livros serão removidos do seu dispositivo.",
    delete: "Excluir",
    appearance: "Aparência",
    readingTheme: "Tema de leitura",
    customizeExperience: "Personalize sua experiência",
    version: "Versão",
    myAccount: "Minha conta",
    comingSoon: "Em breve",
    search: "Buscar",
    searchConversations: "Buscar conversas...",
    noConversations: "Sem conversas",
    startConversation: "Inicie uma conversa com outro usuário",
    newConversation: "Nova conversa",
    now: "Agora",
    yesterday: "Ontem",
    noMessages: "Sem mensagens",
    publications: "Publicações",
    create: "Criar",
    newPost: "Nova publicação",
    publish: "Publicar",
    whatToShare: "O que você quer compartilhar?",
    photo: "Foto",
    video: "Vídeo",
    noPostsYet: "Sem publicações ainda",
    beFirst: "Seja o primeiro a compartilhar!",
    createPost: "Criar publicação",
    publishError: "Erro ao publicar",
    published: "Publicado!",
    trending: "Tendências",
    seeMore: "Ver mais",
    recentlyPublished: "Publicados recentemente",
    noBooksYet: "Sem livros ainda",
    categories: "Categorias",
    writeStory: "Escrever história",
    microstories: "Microcontos",
    feedStories: "Feed & Stories",
    publishAndShare: "Publique e compartilhe",
    createPromotion: "Criar Promoção",
    highlightBook: "Destaque seu livro e alcance mais leitores",
    personalizeRecs: "Personalize suas recomendações",
    loadError: "Erro ao carregar conversas",
    privateProfileDesc: "Apenas seus seguidores podem ver seu conteúdo",
    profileStore: "Loja de perfil",
    coins: "moedas",
    totalEarned: "Total ganho",
    earnByEngaging: "Ganhe interagindo",
    comment: "Comentário",
    frames: "Molduras",
    backgrounds: "Fundos",
    notEnoughCoins: "Moedas insuficientes",
    noItemsAvailable: "Nenhum item disponível",
    close: "Fechar",
    store: "Loja",
    back: "Voltar",
    editProfile: "Editar perfil",
    newBook: "Novo livro",
    books: "Livros",
    followers: "Seguidores",
    following: "Seguindo",
    reads: "Leituras",
    inventory: "Inventário",
    profileThemes: "Temas de perfil",
    noBooksYetProfile: "Sem livros ainda",
    startWriting: "Comece a escrever sua primeira história!",
    createBook: "Criar livro",
    deleteBook: "Excluir livro?",
    deleteBookDesc: "Será excluído permanentemente. Esta ação não pode ser desfeita.",
    deleted: "Excluído",
    deleteError: "Erro ao excluir",
    team: "Equipe / Admins",
    teamDesc: "Conheça a equipe por trás do app",
    staffBday: "Staff Bday",
    staffBdayTitle: "Staff Bday",
    staffBdayClosed: "Esta seção está fechada no momento",
    staffContract: "Staff Contract",
    staffContractDesc: "Contratos e formulários da equipe",
    noContracts: "Sem contratos",
    noContractsDesc: "Nenhum contrato disponível no momento.",
    endsAt: "Termina",
    openForm: "Abrir formulário",
    expired: "Expirado",
    active: "Ativo",
    news: "Notícias",
    newsDesc: "Atualizações, patches e novidades",
    noNews: "Sem notícias",
    noNewsDesc: "Nenhuma notícia disponível no momento.",
  },
  fr: {
    home: "Accueil",
    explore: "Explorer",
    library: "Bibliothèque",
    messages: "Messages",
    profile: "Profil",
    settings: "Paramètres",
    darkMode: "Mode sombre",
    language: "Langue",
    notifications: "Notifications",
    pushNotifications: "Notifications push",
    emailNotifications: "Notifications par email",
    privacy: "Confidentialité",
    privateProfile: "Profil privé",
    showReadingActivity: "Afficher l'activité de lecture",
    changePassword: "Changer le mot de passe",
    content: "Contenu",
    favoriteGenres: "Genres préférés",
    favoriteAuthors: "Auteurs préférés",
    storage: "Stockage",
    spaceUsed: "Espace utilisé",
    downloadedBooks: "Livres téléchargés",
    wifiOnly: "Wi-Fi uniquement pour les téléchargements",
    clearCache: "Vider le cache",
    logout: "Se déconnecter",
    logoutConfirm: "Se déconnecter ?",
    logoutDescription: "Vous devrez vous reconnecter pour accéder à votre compte.",
    cancel: "Annuler",
    deleteDownloaded: "Supprimer les livres téléchargés ?",
    deleteDownloadedDesc: "Les livres seront supprimés de votre appareil.",
    delete: "Supprimer",
    appearance: "Apparence",
    readingTheme: "Thème de lecture",
    customizeExperience: "Personnalisez votre expérience",
    version: "Version",
    myAccount: "Mon compte",
    comingSoon: "Bientôt disponible",
    search: "Rechercher",
    searchConversations: "Rechercher des conversations...",
    noConversations: "Aucune conversation",
    startConversation: "Démarrez une conversation avec un autre utilisateur",
    newConversation: "Nouvelle conversation",
    now: "Maintenant",
    yesterday: "Hier",
    noMessages: "Aucun message",
    publications: "Publications",
    create: "Créer",
    newPost: "Nouvelle publication",
    publish: "Publier",
    whatToShare: "Que voulez-vous partager ?",
    photo: "Photo",
    video: "Vidéo",
    noPostsYet: "Aucune publication",
    beFirst: "Soyez le premier à partager !",
    createPost: "Créer une publication",
    publishError: "Erreur de publication",
    published: "Publié !",
    trending: "Tendances",
    seeMore: "Voir plus",
    recentlyPublished: "Récemment publiés",
    noBooksYet: "Pas encore de livres",
    categories: "Catégories",
    writeStory: "Écrire une histoire",
    microstories: "Micro-histoires",
    feedStories: "Feed & Stories",
    publishAndShare: "Publiez et partagez",
    createPromotion: "Créer une Promotion",
    highlightBook: "Mettez en avant votre livre",
    personalizeRecs: "Personnalisez vos recommandations",
    loadError: "Erreur de chargement des conversations",
    privateProfileDesc: "Seuls vos abonnés peuvent voir votre contenu",
    profileStore: "Boutique de profil",
    coins: "pièces",
    totalEarned: "Total gagné",
    earnByEngaging: "Gagnez en interagissant",
    comment: "Commentaire",
    frames: "Cadres",
    backgrounds: "Arrière-plans",
    notEnoughCoins: "Pas assez de pièces",
    noItemsAvailable: "Aucun article disponible",
    close: "Fermer",
    store: "Boutique",
    back: "Retour",
    editProfile: "Modifier le profil",
    newBook: "Nouveau livre",
    books: "Livres",
    followers: "Abonnés",
    following: "Abonnements",
    reads: "Lectures",
    inventory: "Inventaire",
    profileThemes: "Thèmes de profil",
    noBooksYetProfile: "Pas encore de livres",
    startWriting: "Commencez à écrire votre première histoire !",
    createBook: "Créer un livre",
    deleteBook: "Supprimer le livre ?",
    deleteBookDesc: "Il sera supprimé définitivement. Cette action est irréversible.",
    deleted: "Supprimé",
    deleteError: "Erreur de suppression",
    team: "Équipe / Admins",
    teamDesc: "Découvrez l'équipe derrière l'app",
    staffBday: "Staff Bday",
    staffBdayTitle: "Staff Bday",
    staffBdayClosed: "Cette section est actuellement fermée",
    staffContract: "Staff Contract",
    staffContractDesc: "Contrats et formulaires de l'équipe",
    noContracts: "Aucun contrat",
    noContractsDesc: "Aucun contrat disponible pour le moment.",
    endsAt: "Fin",
    openForm: "Ouvrir le formulaire",
    expired: "Expiré",
    active: "Actif",
    news: "Actualités",
    newsDesc: "Mises à jour, correctifs et nouveautés",
    noNews: "Aucune actualité",
    noNewsDesc: "Aucune actualité disponible pour le moment.",
  },
  it: {
    home: "Home",
    explore: "Esplora",
    library: "Biblioteca",
    messages: "Messaggi",
    profile: "Profilo",
    settings: "Impostazioni",
    darkMode: "Modalità scura",
    language: "Lingua",
    notifications: "Notifiche",
    pushNotifications: "Notifiche push",
    emailNotifications: "Notifiche via email",
    privacy: "Privacy",
    privateProfile: "Profilo privato",
    showReadingActivity: "Mostra attività di lettura",
    changePassword: "Cambia password",
    content: "Contenuto",
    favoriteGenres: "Generi preferiti",
    favoriteAuthors: "Autori preferiti",
    storage: "Archiviazione",
    spaceUsed: "Spazio utilizzato",
    downloadedBooks: "Libri scaricati",
    wifiOnly: "Solo Wi-Fi per i download",
    clearCache: "Svuota cache",
    logout: "Esci",
    logoutConfirm: "Uscire?",
    logoutDescription: "Dovrai accedere di nuovo per usare il tuo account.",
    cancel: "Annulla",
    deleteDownloaded: "Eliminare i libri scaricati?",
    deleteDownloadedDesc: "I libri verranno rimossi dal tuo dispositivo.",
    delete: "Elimina",
    appearance: "Aspetto",
    readingTheme: "Tema di lettura",
    customizeExperience: "Personalizza la tua esperienza",
    version: "Versione",
    myAccount: "Il mio account",
    comingSoon: "Prossimamente",
    search: "Cerca",
    searchConversations: "Cerca conversazioni...",
    noConversations: "Nessuna conversazione",
    startConversation: "Inizia una conversazione con un altro utente",
    newConversation: "Nuova conversazione",
    now: "Ora",
    yesterday: "Ieri",
    noMessages: "Nessun messaggio",
    publications: "Pubblicazioni",
    create: "Crea",
    newPost: "Nuova pubblicazione",
    publish: "Pubblica",
    whatToShare: "Cosa vuoi condividere?",
    photo: "Foto",
    video: "Video",
    noPostsYet: "Nessuna pubblicazione",
    beFirst: "Sii il primo a condividere!",
    createPost: "Crea pubblicazione",
    publishError: "Errore di pubblicazione",
    published: "Pubblicato!",
    trending: "Tendenze",
    seeMore: "Vedi di più",
    recentlyPublished: "Pubblicati di recente",
    noBooksYet: "Nessun libro ancora",
    categories: "Categorie",
    writeStory: "Scrivi storia",
    microstories: "Microstorie",
    feedStories: "Feed & Stories",
    publishAndShare: "Pubblica e condividi",
    createPromotion: "Crea Promozione",
    highlightBook: "Metti in evidenza il tuo libro",
    personalizeRecs: "Personalizza i tuoi consigli",
    loadError: "Errore nel caricamento delle conversazioni",
    privateProfileDesc: "Solo i tuoi follower possono vedere i tuoi contenuti",
    profileStore: "Negozio profilo",
    coins: "monete",
    totalEarned: "Totale guadagnato",
    earnByEngaging: "Guadagna interagendo",
    comment: "Commento",
    frames: "Cornici",
    backgrounds: "Sfondi",
    notEnoughCoins: "Monete insufficienti",
    noItemsAvailable: "Nessun articolo disponibile",
    close: "Chiudi",
    store: "Negozio",
    back: "Indietro",
    editProfile: "Modifica profilo",
    newBook: "Nuovo libro",
    books: "Libri",
    followers: "Follower",
    following: "Seguiti",
    reads: "Letture",
    inventory: "Inventario",
    profileThemes: "Temi profilo",
    noBooksYetProfile: "Nessun libro ancora",
    startWriting: "Inizia a scrivere la tua prima storia!",
    createBook: "Crea libro",
    deleteBook: "Eliminare il libro?",
    deleteBookDesc: "Verrà eliminato definitivamente. Questa azione non può essere annullata.",
    deleted: "Eliminato",
    deleteError: "Errore durante l'eliminazione",
    team: "Team / Admins",
    teamDesc: "Scopri il team dietro l'app",
    staffBday: "Staff Bday",
    staffBdayTitle: "Staff Bday",
    staffBdayClosed: "Questa sezione è attualmente chiusa",
    staffContract: "Staff Contract",
    staffContractDesc: "Contratti e moduli del team",
    noContracts: "Nessun contratto",
    noContractsDesc: "Nessun contratto disponibile al momento.",
    endsAt: "Scade",
    openForm: "Apri modulo",
    expired: "Scaduto",
    active: "Attivo",
    news: "Notizie",
    newsDesc: "Aggiornamenti, patch e novità",
    noNews: "Nessuna notizia",
    noNewsDesc: "Nessuna notizia disponibile al momento.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageNames: Record<Language, string>;
  availableLanguages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(LANG_KEY);
    return (saved as Language) || "es";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, []);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.es[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languageNames,
        availableLanguages: ["es", "en", "pt", "fr", "it"],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
